---
root: true
extends: eslint:recommended
env:
  es2022: true
  node: true
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - prettier
rules:
  prettier/prettier: error
  quotes: off
  semi: off
overrides:
  - files:
    - '*.spec.js'
    env:
      jasmine: true
